version: '3.8'
name: survey-test-api
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ../../../data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: test
  rest-api:
    image: rest-api
    build:
      context: ../../..
      dockerfile: Dockerfile
      args:
        INTEGRATE_NGINX: "true"
    restart: always
    ports:
      - "5000:80"
    environment:
      # general
      DEBUG: "app:*,express:false"
      META: true
      PORT: 5000
      ARTIFICIAL_DELAY: -1
      # database
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_USER: admin
      DATABASE_PASSWORD: admin
      DATABASE_DB: test
      # authentication
      ACCESS_TOKEN_SECRET: access_token_dummy
      ACCESS_TOKEN_EXPIRATION: 3600
      REFRESH_TOKEN_SECRET: refresh_token_dummy
      REFRESH_TOKEN_EXPIRATION: 86400
      # paging
      MAX_PER_PAGE: 30
