name: survey-test-backend
services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: test
    volumes:
      - ../mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ../../../data:/data/db
  rest-api:
    image: survey-test-api:latest
    build:
      context: ../../..
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:80"
    environment:
      # enable colors for logging (debug package)
      DEBUG_COLORS: true
      # forward logging to stdout (debug package)
      DEBUG_FD: 1
    volumes:
      # IMPORTANT: database host needs to be 'mongo' to connect to dockerized MongoDB
      - ../../../.env:/home/www/node/build/.env:ro
