version: '3.8'
name: survey-test-api
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ../../../data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  rest-api:
    image: rest-api
    build:
      context: ../../..
      dockerfile: Dockerfile
      args:
        INTEGRATE_NGINX: "false"
    restart: always
    ports:
      - "5000:5000"
    environment:
      # general
      DEBUG: "app:*,express:false"
      META: false
      PORT: 5000
      # artificial delay
      ARTIFICIAL_DELAY: -1
      # database
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_USER: admin
      DATABASE_PASSWORD: admin
      DATABASE_DB: test
      # authentication
      ACCESS_TOKEN_SECRET: access_1234
      ACCESS_TOKEN_EXPIRATION: 3600
      REFRESH_TOKEN_SECRET: refresh_1234
      REFRESH_TOKEN_EXPIRATION: 86400
      # paging
      MAX_PER_PAGE: 10
