name: Push - Build

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

jobs:
  build:
    name: Build API
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Node Packages
        run: npm ci --no-fund
      - name: Build Node App
        run: npm run build
      - name: Upload Build Assets
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist
          retention-days: 3
