name: Tag - Build Docker & Publish Image

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    name: Build and Publish Docker Image
    runs-on: ubuntu-20.04
    env:
      REPO: ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_REPOSITORY }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Login to Docker Registry
        run: docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_USERNAME }}
          -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t $REPO:${GITHUB_REF_NAME} -t $REPO:latest .
      - name: Publish Docker Image
        run: docker push $REPO
