name: Tag - Build & Publish Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    name: Build and Publish Docker Image
    runs-on: ubuntu-20.04
    env:
      REPO: ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_REPOSITORY }}
    steps:
      - name: Get Tag Name
        id: get_tag_name
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.get_tag_name.outputs.VERSION }}
      - name: Login to Docker Registry
        run: docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_USERNAME }}
          -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t $REPO:${{ steps.get_tag_name.outputs.VERSION }} .
      - name: Publish Docker Image
        run: docker push $REPO:${{ steps.get_tag_name.outputs.VERSION }}
